use_frameworks!

platform :ios, '10.0'

target 'HYUIKitRuntimeUtils_Example' do
  pod 'HYUIKitRuntimeUtils', :path => '../'

  target 'HYUIKitRuntimeUtils_Tests' do
    inherit! :search_paths

    
  end
  
  post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.read(xcconfig_path)
        xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
        File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
        if t.name.include?('HandyJSON')
          config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '0'
          config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
        end
      end
    end
  end
  
end
